package repository;

import dto.ApiToken;
import dto.ApiTokenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.mybatis.cdi.Mapper;

@Mapper
public interface ApiTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.api_token
     *
     * @mbg.generated
     */
    long countByExample(ApiTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.api_token
     *
     * @mbg.generated
     */
    int deleteByExample(ApiTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.api_token
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String originContext);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.api_token
     *
     * @mbg.generated
     */
    int insert(ApiToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.api_token
     *
     * @mbg.generated
     */
    int insertSelective(ApiToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.api_token
     *
     * @mbg.generated
     */
    List<ApiToken> selectByExampleWithRowbounds(ApiTokenExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.api_token
     *
     * @mbg.generated
     */
    List<ApiToken> selectByExample(ApiTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.api_token
     *
     * @mbg.generated
     */
    ApiToken selectByPrimaryKey(String originContext);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.api_token
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ApiToken record, @Param("example") ApiTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.api_token
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ApiToken record, @Param("example") ApiTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.api_token
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ApiToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.api_token
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ApiToken record);
}