package repository;

import dto.Chatter;
import dto.ChatterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.mybatis.cdi.Mapper;

@Mapper
public interface ChatterMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.chatter
     * @mbg.generated
     */
    long countByExample(ChatterExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.chatter
     * @mbg.generated
     */
    int deleteByExample(ChatterExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.chatter
     * @mbg.generated
     */
    int insert(Chatter record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.chatter
     * @mbg.generated
     */
    int insertSelective(Chatter record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.chatter
     * @mbg.generated
     */
    List<Chatter> selectByExampleWithRowbounds(ChatterExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.chatter
     * @mbg.generated
     */
    List<Chatter> selectByExample(ChatterExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.chatter
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Chatter record, @Param("example") ChatterExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.chatter
     * @mbg.generated
     */
    int updateByExample(@Param("record") Chatter record, @Param("example") ChatterExample example);
}