package repository;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.mybatis.cdi.Mapper;

import dto.LoginedUser;
import dto.LoginedUserExample;

@Mapper
public interface LoginedUserMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.logined_user
     * @mbg.generated
     */
    long countByExample(LoginedUserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.logined_user
     * @mbg.generated
     */
    int deleteByExample(LoginedUserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.logined_user
     * @mbg.generated
     */
    int deleteByPrimaryKey(String sessionId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.logined_user
     * @mbg.generated
     */
    int insert(LoginedUser record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.logined_user
     * @mbg.generated
     */
    int insertSelective(LoginedUser record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.logined_user
     * @mbg.generated
     */
    List<LoginedUser> selectByExampleWithRowbounds(LoginedUserExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.logined_user
     * @mbg.generated
     */
    List<LoginedUser> selectByExample(LoginedUserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.logined_user
     * @mbg.generated
     */
    LoginedUser selectByPrimaryKey(String sessionId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.logined_user
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LoginedUser record, @Param("example") LoginedUserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.logined_user
     * @mbg.generated
     */
    int updateByExample(@Param("record") LoginedUser record, @Param("example") LoginedUserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.logined_user
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LoginedUser record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.logined_user
     * @mbg.generated
     */
    int updateByPrimaryKey(LoginedUser record);
}
