package dto;

/**
 * Database Table Remarks:
 *   APIトークン
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table public.api_token
 */
public class ApiToken {
    /**
     * Database Column Remarks:
     *   オリジンコンテントルート
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.api_token.origin_context
     *
     * @mbg.generated
     */
    private String originContext;

    /**
     * Database Column Remarks:
     *   APIトークン
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.api_token.api_token
     *
     * @mbg.generated
     */
    private String apiToken;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.api_token.origin_context
     *
     * @return the value of public.api_token.origin_context
     *
     * @mbg.generated
     */
    public String getOriginContext() {
        return originContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.api_token.origin_context
     *
     * @param originContext the value for public.api_token.origin_context
     *
     * @mbg.generated
     */
    public void setOriginContext(String originContext) {
        this.originContext = originContext == null ? null : originContext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.api_token.api_token
     *
     * @return the value of public.api_token.api_token
     *
     * @mbg.generated
     */
    public String getApiToken() {
        return apiToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.api_token.api_token
     *
     * @param apiToken the value for public.api_token.api_token
     *
     * @mbg.generated
     */
    public void setApiToken(String apiToken) {
        this.apiToken = apiToken == null ? null : apiToken.trim();
    }
}