package dto;

import java.util.ArrayList;
import java.util.List;

public class ApiTokenExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.api_token
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.api_token
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.api_token
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.api_token
     *
     * @mbg.generated
     */
    public ApiTokenExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.api_token
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.api_token
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.api_token
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.api_token
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.api_token
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.api_token
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.api_token
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.api_token
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.api_token
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.api_token
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.api_token
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOriginContextIsNull() {
            addCriterion("origin_context is null");
            return (Criteria) this;
        }

        public Criteria andOriginContextIsNotNull() {
            addCriterion("origin_context is not null");
            return (Criteria) this;
        }

        public Criteria andOriginContextEqualTo(String value) {
            addCriterion("origin_context =", value, "originContext");
            return (Criteria) this;
        }

        public Criteria andOriginContextNotEqualTo(String value) {
            addCriterion("origin_context <>", value, "originContext");
            return (Criteria) this;
        }

        public Criteria andOriginContextGreaterThan(String value) {
            addCriterion("origin_context >", value, "originContext");
            return (Criteria) this;
        }

        public Criteria andOriginContextGreaterThanOrEqualTo(String value) {
            addCriterion("origin_context >=", value, "originContext");
            return (Criteria) this;
        }

        public Criteria andOriginContextLessThan(String value) {
            addCriterion("origin_context <", value, "originContext");
            return (Criteria) this;
        }

        public Criteria andOriginContextLessThanOrEqualTo(String value) {
            addCriterion("origin_context <=", value, "originContext");
            return (Criteria) this;
        }

        public Criteria andOriginContextLike(String value) {
            addCriterion("origin_context like", value, "originContext");
            return (Criteria) this;
        }

        public Criteria andOriginContextNotLike(String value) {
            addCriterion("origin_context not like", value, "originContext");
            return (Criteria) this;
        }

        public Criteria andOriginContextIn(List<String> values) {
            addCriterion("origin_context in", values, "originContext");
            return (Criteria) this;
        }

        public Criteria andOriginContextNotIn(List<String> values) {
            addCriterion("origin_context not in", values, "originContext");
            return (Criteria) this;
        }

        public Criteria andOriginContextBetween(String value1, String value2) {
            addCriterion("origin_context between", value1, value2, "originContext");
            return (Criteria) this;
        }

        public Criteria andOriginContextNotBetween(String value1, String value2) {
            addCriterion("origin_context not between", value1, value2, "originContext");
            return (Criteria) this;
        }

        public Criteria andApiTokenIsNull() {
            addCriterion("api_token is null");
            return (Criteria) this;
        }

        public Criteria andApiTokenIsNotNull() {
            addCriterion("api_token is not null");
            return (Criteria) this;
        }

        public Criteria andApiTokenEqualTo(String value) {
            addCriterion("api_token =", value, "apiToken");
            return (Criteria) this;
        }

        public Criteria andApiTokenNotEqualTo(String value) {
            addCriterion("api_token <>", value, "apiToken");
            return (Criteria) this;
        }

        public Criteria andApiTokenGreaterThan(String value) {
            addCriterion("api_token >", value, "apiToken");
            return (Criteria) this;
        }

        public Criteria andApiTokenGreaterThanOrEqualTo(String value) {
            addCriterion("api_token >=", value, "apiToken");
            return (Criteria) this;
        }

        public Criteria andApiTokenLessThan(String value) {
            addCriterion("api_token <", value, "apiToken");
            return (Criteria) this;
        }

        public Criteria andApiTokenLessThanOrEqualTo(String value) {
            addCriterion("api_token <=", value, "apiToken");
            return (Criteria) this;
        }

        public Criteria andApiTokenLike(String value) {
            addCriterion("api_token like", value, "apiToken");
            return (Criteria) this;
        }

        public Criteria andApiTokenNotLike(String value) {
            addCriterion("api_token not like", value, "apiToken");
            return (Criteria) this;
        }

        public Criteria andApiTokenIn(List<String> values) {
            addCriterion("api_token in", values, "apiToken");
            return (Criteria) this;
        }

        public Criteria andApiTokenNotIn(List<String> values) {
            addCriterion("api_token not in", values, "apiToken");
            return (Criteria) this;
        }

        public Criteria andApiTokenBetween(String value1, String value2) {
            addCriterion("api_token between", value1, value2, "apiToken");
            return (Criteria) this;
        }

        public Criteria andApiTokenNotBetween(String value1, String value2) {
            addCriterion("api_token not between", value1, value2, "apiToken");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.api_token
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.api_token
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}