package dto;

import java.time.LocalDateTime;

/**
 * Database Table Remarks:
 *   チャット
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table public.chatter
 */
public class Chatter {

    /**
     * Database Column Remarks: グループID This field was generated by MyBatis Generator. This field corresponds to the database column public.chatter.group_id
     * @mbg.generated
     */
    private String groupId;
    /**
     * Database Column Remarks: ユーザID This field was generated by MyBatis Generator. This field corresponds to the database column public.chatter.user_id
     * @mbg.generated
     */
    private String userId;
    /**
     * Database Column Remarks: メッセージ This field was generated by MyBatis Generator. This field corresponds to the database column public.chatter.message
     * @mbg.generated
     */
    private String message;
    /**
     * Database Column Remarks: 作成日時 This field was generated by MyBatis Generator. This field corresponds to the database column public.chatter.createdtime
     * @mbg.generated
     */
    private LocalDateTime createdtime;
    /**
     * Database Column Remarks: 更新日時 This field was generated by MyBatis Generator. This field corresponds to the database column public.chatter.updatedtime
     * @mbg.generated
     */
    private LocalDateTime updatedtime;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column public.chatter.group_id
     * @return  the value of public.chatter.group_id
     * @mbg.generated
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column public.chatter.group_id
     * @param groupId  the value for public.chatter.group_id
     * @mbg.generated
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column public.chatter.user_id
     * @return  the value of public.chatter.user_id
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column public.chatter.user_id
     * @param userId  the value for public.chatter.user_id
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column public.chatter.message
     * @return  the value of public.chatter.message
     * @mbg.generated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column public.chatter.message
     * @param message  the value for public.chatter.message
     * @mbg.generated
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column public.chatter.createdtime
     * @return  the value of public.chatter.createdtime
     * @mbg.generated
     */
    public LocalDateTime getCreatedtime() {
        return createdtime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column public.chatter.createdtime
     * @param createdtime  the value for public.chatter.createdtime
     * @mbg.generated
     */
    public void setCreatedtime(LocalDateTime createdtime) {
        this.createdtime = createdtime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column public.chatter.updatedtime
     * @return  the value of public.chatter.updatedtime
     * @mbg.generated
     */
    public LocalDateTime getUpdatedtime() {
        return updatedtime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column public.chatter.updatedtime
     * @param updatedtime  the value for public.chatter.updatedtime
     * @mbg.generated
     */
    public void setUpdatedtime(LocalDateTime updatedtime) {
        this.updatedtime = updatedtime;
    }
}
