package dto;

import java.time.LocalDateTime;

/**
 * Database Table Remarks:
 *   トークン
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table public.token
 */
public class Token {
    /**
     * Database Column Remarks:
     *   トークン
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.token.token
     *
     * @mbg.generated
     */
    private String token;

    /**
     * Database Column Remarks:
     *   作成日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.token.createdtime
     *
     * @mbg.generated
     */
    private LocalDateTime createdtime;

    /**
     * Database Column Remarks:
     *   更新日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.token.updatedtime
     *
     * @mbg.generated
     */
    private LocalDateTime updatedtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.token.token
     *
     * @return the value of public.token.token
     *
     * @mbg.generated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.token.token
     *
     * @param token the value for public.token.token
     *
     * @mbg.generated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.token.createdtime
     *
     * @return the value of public.token.createdtime
     *
     * @mbg.generated
     */
    public LocalDateTime getCreatedtime() {
        return createdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.token.createdtime
     *
     * @param createdtime the value for public.token.createdtime
     *
     * @mbg.generated
     */
    public void setCreatedtime(LocalDateTime createdtime) {
        this.createdtime = createdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.token.updatedtime
     *
     * @return the value of public.token.updatedtime
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdatedtime() {
        return updatedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.token.updatedtime
     *
     * @param updatedtime the value for public.token.updatedtime
     *
     * @mbg.generated
     */
    public void setUpdatedtime(LocalDateTime updatedtime) {
        this.updatedtime = updatedtime;
    }
}