package dto;

import java.time.LocalDateTime;

/**
 * Database Table Remarks:
 *   ユーザ情報
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table public.user_info
 */
public class UserInfo {
    /**
     * Database Column Remarks:
     *   ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user_info.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   パスワード
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user_info.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     * Database Column Remarks:
     *   Eメールアドレス
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user_info.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     * Database Column Remarks:
     *   新規Eメールアドレス
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user_info.email_new
     *
     * @mbg.generated
     */
    private String emailNew;

    /**
     * Database Column Remarks:
     *   姓
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user_info.last_name
     *
     * @mbg.generated
     */
    private String lastName;

    /**
     * Database Column Remarks:
     *   名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user_info.first_name
     *
     * @mbg.generated
     */
    private String firstName;

    /**
     * Database Column Remarks:
     *   郵便番号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user_info.postal_code
     *
     * @mbg.generated
     */
    private String postalCode;

    /**
     * Database Column Remarks:
     *   都道府県
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user_info.region
     *
     * @mbg.generated
     */
    private String region;

    /**
     * Database Column Remarks:
     *   市区町村
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user_info.locality
     *
     * @mbg.generated
     */
    private String locality;

    /**
     * Database Column Remarks:
     *   町域
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user_info.street_address
     *
     * @mbg.generated
     */
    private String streetAddress;

    /**
     * Database Column Remarks:
     *   その他住所
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user_info.extended_address
     *
     * @mbg.generated
     */
    private String extendedAddress;

    /**
     * Database Column Remarks:
     *   認証失敗回数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user_info.fail_count
     *
     * @mbg.generated
     */
    private Integer failCount;

    /**
     * Database Column Remarks:
     *   アカウント解除日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user_info.unlocked_date_time
     *
     * @mbg.generated
     */
    private LocalDateTime unlockedDateTime;

    /**
     * Database Column Remarks:
     *   アカウントロックフラグ
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user_info.locked
     *
     * @mbg.generated
     */
    private Boolean locked;

    /**
     * Database Column Remarks:
     *   バージョン
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user_info.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     * Database Column Remarks:
     *   作成日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user_info.createdtime
     *
     * @mbg.generated
     */
    private LocalDateTime createdtime;

    /**
     * Database Column Remarks:
     *   更新日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user_info.updatedtime
     *
     * @mbg.generated
     */
    private LocalDateTime updatedtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user_info.id
     *
     * @return the value of public.user_info.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user_info.id
     *
     * @param id the value for public.user_info.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user_info.password
     *
     * @return the value of public.user_info.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user_info.password
     *
     * @param password the value for public.user_info.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user_info.email
     *
     * @return the value of public.user_info.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user_info.email
     *
     * @param email the value for public.user_info.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user_info.email_new
     *
     * @return the value of public.user_info.email_new
     *
     * @mbg.generated
     */
    public String getEmailNew() {
        return emailNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user_info.email_new
     *
     * @param emailNew the value for public.user_info.email_new
     *
     * @mbg.generated
     */
    public void setEmailNew(String emailNew) {
        this.emailNew = emailNew == null ? null : emailNew.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user_info.last_name
     *
     * @return the value of public.user_info.last_name
     *
     * @mbg.generated
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user_info.last_name
     *
     * @param lastName the value for public.user_info.last_name
     *
     * @mbg.generated
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user_info.first_name
     *
     * @return the value of public.user_info.first_name
     *
     * @mbg.generated
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user_info.first_name
     *
     * @param firstName the value for public.user_info.first_name
     *
     * @mbg.generated
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName == null ? null : firstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user_info.postal_code
     *
     * @return the value of public.user_info.postal_code
     *
     * @mbg.generated
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user_info.postal_code
     *
     * @param postalCode the value for public.user_info.postal_code
     *
     * @mbg.generated
     */
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode == null ? null : postalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user_info.region
     *
     * @return the value of public.user_info.region
     *
     * @mbg.generated
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user_info.region
     *
     * @param region the value for public.user_info.region
     *
     * @mbg.generated
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user_info.locality
     *
     * @return the value of public.user_info.locality
     *
     * @mbg.generated
     */
    public String getLocality() {
        return locality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user_info.locality
     *
     * @param locality the value for public.user_info.locality
     *
     * @mbg.generated
     */
    public void setLocality(String locality) {
        this.locality = locality == null ? null : locality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user_info.street_address
     *
     * @return the value of public.user_info.street_address
     *
     * @mbg.generated
     */
    public String getStreetAddress() {
        return streetAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user_info.street_address
     *
     * @param streetAddress the value for public.user_info.street_address
     *
     * @mbg.generated
     */
    public void setStreetAddress(String streetAddress) {
        this.streetAddress = streetAddress == null ? null : streetAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user_info.extended_address
     *
     * @return the value of public.user_info.extended_address
     *
     * @mbg.generated
     */
    public String getExtendedAddress() {
        return extendedAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user_info.extended_address
     *
     * @param extendedAddress the value for public.user_info.extended_address
     *
     * @mbg.generated
     */
    public void setExtendedAddress(String extendedAddress) {
        this.extendedAddress = extendedAddress == null ? null : extendedAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user_info.fail_count
     *
     * @return the value of public.user_info.fail_count
     *
     * @mbg.generated
     */
    public Integer getFailCount() {
        return failCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user_info.fail_count
     *
     * @param failCount the value for public.user_info.fail_count
     *
     * @mbg.generated
     */
    public void setFailCount(Integer failCount) {
        this.failCount = failCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user_info.unlocked_date_time
     *
     * @return the value of public.user_info.unlocked_date_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUnlockedDateTime() {
        return unlockedDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user_info.unlocked_date_time
     *
     * @param unlockedDateTime the value for public.user_info.unlocked_date_time
     *
     * @mbg.generated
     */
    public void setUnlockedDateTime(LocalDateTime unlockedDateTime) {
        this.unlockedDateTime = unlockedDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user_info.locked
     *
     * @return the value of public.user_info.locked
     *
     * @mbg.generated
     */
    public Boolean getLocked() {
        return locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user_info.locked
     *
     * @param locked the value for public.user_info.locked
     *
     * @mbg.generated
     */
    public void setLocked(Boolean locked) {
        this.locked = locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user_info.version
     *
     * @return the value of public.user_info.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user_info.version
     *
     * @param version the value for public.user_info.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user_info.createdtime
     *
     * @return the value of public.user_info.createdtime
     *
     * @mbg.generated
     */
    public LocalDateTime getCreatedtime() {
        return createdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user_info.createdtime
     *
     * @param createdtime the value for public.user_info.createdtime
     *
     * @mbg.generated
     */
    public void setCreatedtime(LocalDateTime createdtime) {
        this.createdtime = createdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user_info.updatedtime
     *
     * @return the value of public.user_info.updatedtime
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdatedtime() {
        return updatedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user_info.updatedtime
     *
     * @param updatedtime the value for public.user_info.updatedtime
     *
     * @mbg.generated
     */
    public void setUpdatedtime(LocalDateTime updatedtime) {
        this.updatedtime = updatedtime;
    }
}
